### ISSUE TITLE
persistent deprecation warning in IJulia

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaPlots/PlotUtils.jl#10]
On Julia v0.6, changing the:
```julia
Array(RGBA{Float64}, size(cs))
```
to:
```julia
Array{RGBA{Float64}}(size(cs))
```
in colors.jl fixes things, similarly in ticks.jl (two instances of `Array{typeof(1.0 * one_t)}(Int(3 * k_best))`).

**Comment by mkborregaard** [comment]
Feel like opening a PR?

**Comment by dpsanders** [comment]
See #12.

**Comment by MikaelSlevinsky** [comment]
Thanks!
