### ISSUE TITLE
zscale test failures

### ISSUE THREAD

**Issue by mileslucas** [JuliaPlots/PlotUtils.jl#111]
As pointed out in #110 `zscale` tests are failing on julia nightly. This is almost certainly due to random number generation changing, which invalidates the hard-coded values we test against. There's a few ways to fix this and I'm happy to PR, but I want the maintainers to weigh the options before I start.

1. The first option is to add `StableRNGs.jl` as a test dependency and change all the random number generation. This may affect other tests, so I'm not sure how annoying that would be, but I think this is the best option.

2. The next option is to add another `if-else` branch in the test (there already is one), but frankly the current number generation isn't even seeded, so I think this is a fragile solution at best.

3. The last option would be to loosen the test restrictions, either testing the values are within some range or switching to very basic tests that ensure the output is finite and within the input range. This is the simplest and least-breaking option, but greatly diminishes the quality of the testing.

Thoughts?

**Comment by BeastyBlacksmith** [comment]
I'd be in favor of 1.

**Comment by daschw** [comment]
Agreed.
