### ISSUE TITLE
optimize_ticks not working right for small values

### ISSUE THREAD

**Issue by isentropic** [JuliaPlots/PlotUtils.jl#114]
```julia
optimize_ticks(-1e-10, 1e-10)
([-1.0e-10, 0.0, 1.0e-10], -1.0e-10, 1.0e-10)  # looks fine

optimize_ticks(-1e-16, 1e-16)
([-1.0e-16], -1.0, 0.9999999999999999)  # pretty bad, should at least return 2 ticks.

```
In short, I strongly think that optimize_ticks should at least return 2 arguments (the worst case), but never 1 tick. @mkborregaard looks like you have the most commit lines here perhaps you could know the reason why this happens?

This is related to https://github.com/JuliaPlots/Plots.jl/issues/1858, not the formatting part (which will be fixed in Showoff pretty soon), but the fact that only 1 tick is returned which looks very odd to me :thinking:. I nailed down to this function that sometimes returns only 1 tick

**Comment by mkborregaard** [comment]
I'm not sure, no. It's been a while since I looked at this code.
