### ISSUE TITLE
The `n_points` value in `adapted_grid.jl`

### ISSUE THREAD

**Issue by jverzani** [JuliaPlots/PlotUtils.jl#23]
@KristofferC 

I find that graphs of functions now look decidedly blocky:

![screen shot 2017-07-24 at 4 36 39 pm](https://user-images.githubusercontent.com/421708/28543620-563a20bc-708e-11e7-8565-92b2bb5245e7.png)

I believe it is attributable to the smallish [value](https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/adapted_grid.jl#L24
) for `n_points` in `adapted_grid`. If this is so, would it be possible to bump this value up?

**Comment by KristofferC** [comment]
This need to be in a tag: https://github.com/JuliaPlots/PlotUtils.jl/commit/d9229099b35a7792d73227692e23eaa369d0f8e7

**Comment by KristofferC** [comment]
Right now it does 0 refinements

**Comment by KristofferC** [comment]
Always

**Comment by jverzani** [comment]
That makes sense. Thanks. Will there be a new tag soon? We are setting up labs from an image so it will be easier to checkout a tagged version for us, but we can work with master if need be.

**Comment by KristofferC** [comment]
I am not really involved in this project so I can't say much when stuff will be tagged.

**Comment by jverzani** [comment]
Okay, anyways, this looks really great once integrated in.

**Comment by KristofferC** [comment]
For reference, here it is on master:

![image](https://user-images.githubusercontent.com/1282691/28545061-cdaa4a14-70c5-11e7-8bb2-ee92511f1b66.png)

**Comment by jverzani** [comment]
Yes, it looks really nice with the adaptive sampling!
