### ISSUE TITLE
adapted_grid sometimes off for functions

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/PlotUtils.jl#27]
When passing a function along with xmin and xmax values, the adapted_grid framework sometimes gives too few points. MWE:
```julia
using Plots
plot(sin, -pi, pi)
```
<img width="530" alt="skaermbillede 2017-08-27 kl 21 10 59" src="https://user-images.githubusercontent.com/8429802/29753212-7806823c-8b6c-11e7-95a0-6f286947a7d8.png">
cc @KristofferC

**Comment by KristofferC** [comment]
This is what I get:

![image](https://user-images.githubusercontent.com/1282691/30315530-935faefc-97a4-11e7-9738-cbf795c8caaa.png)

**Comment by mkborregaard** [comment]
It really varies a lot from time to time - here are two different realisations of `plot(sin, -pi, pi, markershape = :circle)`
![skaermbillede 2017-09-12 kl 10 43 50](https://user-images.githubusercontent.com/8429802/30316465-9e39ce72-97a7-11e7-804e-44b15687a0ca.png)
![skaermbillede 2017-09-12 kl 10 45 23](https://user-images.githubusercontent.com/8429802/30316483-ad64118c-97a7-11e7-85ab-6cfc0a5a84ae.png)

**Comment by KristofferC** [comment]
Perhaps  the `rand_factor` at https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/adapted_grid.jl#L35 should be lowered.

**Comment by mkborregaard** [comment]
Adjusting it to 0.01 does seem to improve slightly, but I still got this on my 10th repetition
![skaermbillede 2017-09-12 kl 12 09 29](https://user-images.githubusercontent.com/8429802/30320573-5731e1de-97b3-11e7-9254-fc59af0eef6b.png)

**Comment by mkborregaard** [comment]
It's actually quite mysterious - the rng is seeded with 1337 every time the function is called, so `xs` is always the same here: https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/adapted_grid.jl#L34-L38 (I checked, they are always the same). AFAICS, though, that is the only call to random numbers in the function. Yet, the results are different every time:
```julia
julia> [length(adapted_grid(sin, (-pi, pi))) for i in 1:20]
20-element Array{Int64,1}:
 503
 493
 527
 527
 527
 527
 489
 489
 217
 217
 489
 489
 489
 489
 489
 489
 489
 489
 489
 ´´´
I really can't see where that instability comes from.

**Comment by mkborregaard** [comment]
Hah, the reason was that several of the arrays were not initialized with any values. It was particularly bad for `curvatures`, the array controlling the operation, as the elements were never explicitly assigned to with anything but `+=` - meaning that the exact value depended on whatever garbage it was initialized with. With #29 we get this every time:
<img width="573" alt="skaermbillede 2017-09-14 kl 17 41 55" src="https://user-images.githubusercontent.com/8429802/30439523-5164ef0e-9974-11e7-90ea-fa7394f4e494.png">

**Comment by KristofferC** [comment]
wow, nice catch!

**Comment by mkborregaard** [comment]
Yes it looks great 👍
