### ISSUE TITLE
Enhancing color gradient support

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/PlotUtils.jl#3]
I suggest enhancing the interface for color gradients. I will try to implement this myself, so this issue is to discuss the applicability and the interface.

The suggested interface is a magic attribute (`color`?) with the following elements:
- [x] `color`    : the name of the gradient, e.g. `:magma`, but also offers 
  - [x] `:default`    : the default value, probably equal to `:sequential`
  - [x] `:sequential` : a sequential gradient, such as `:magma`
  - [x] `:diverging`  : a diverging gradient, such as `:redsblues`, e.g. used when the color variable is a standard variation
  - [ ] `:dark`       : or something else - this is an example of other defaults that may be implemented
- [x] `collection`: the gradient collection to look in; see issue #4 
- [ ] `clim`     : the current clim argument but with extra keywords for common specifications
  - [ ] `:max_0`  : clims are `[minimum(x), 0]`, where x is the vector of values for the colors
  - [ ] `:min_0`  : clims are `[0, maximum(x)]`
  - [ ] `:center_0`: clims are `[-y, y]`; `y = maximum(abs([extrema(x)...]))`
- [ ] `gradtype`    : one of
  - [x] `:stretched`  : the current default, choose colors from a continuous gradient
  - [ ] `:equal_interval` : divide the numerical gradient into `classes`number of bins (makes it easier to read values from plots). The default when `classes` is an integer
  - [ ] `:classified` : a common synonym for `:equal_interval`
  - [ ] `:quantiles`  : divide x into `classes` bins with the same number of observations in each
  - [ ] `:custom`     : rarely specified directly, but the default when `classes` is passed a vector. Useful for e.g. `classes =  [-2, 1, 0, 1, 2]` when the color reflects a standard deviation (or other standardized measure)
- [ ] `classes`     : can take either
  - [ ] an `Int` specifying the number of bins for `:equal_interval` and `:quantiles`
  - [ ] a `Vector{T <: Number}` specifying custom break points for the color scales. If `gradtype` is `:quantiles` this may be a vector of percentile values (e.g. `classes = [0.025, 0.5, 0.975]`)

This interface would allow the users to use color much more succinctly and powerfully for scientific graphing, choropleths etc.

Note that the `:color` keyword is currently used to refer to both colors and gradients - with @oxinabox very increased number of named colours it may be necessary to rename to avoid confusion?

**Comment by mkborregaard** [comment]
To implement this, it would be great if someone could direct me to

1. An example of how magic arguments are implemented.
2. How the color bars are communicated to the backend - how much fine-grained control is there for these in Plots?
3. Should some of this be in Plots rather than in PlotUtils?

Thanks.

**Comment by funnell** [comment]
@mkborregaard I wouldn't mind tinkering with gradtype if you can give some pointers on how to get started. My motivation is eventually getting heatmaps with categorical colormaps.

**Comment by mkborregaard** [comment]
Hey that sounds great. Do you mean tinkering with `cgrad`? One way could have a categorical_cgrad type (or a subtype from a common abstract type with cgrad) that would use its `values` field to delimit the categories, just lookup and return the right color?

**Comment by mkborregaard** [comment]
Relevant: https://github.com/JuliaPlots/Plots.jl/issues/383

**Comment by mkborregaard** [comment]
@daschw I think of this as closed by https://github.com/JuliaPlots/PlotUtils.jl/pull/87
Amazing, I really love the functionality now
