### ISSUE TITLE
lims not being well defined in relation to ticks

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/PlotUtils.jl#31]
This issue continues the discussion over on PR #26 .
The comment was:

 it seems as if the axis limits aren't counted as ticks, which I think they should be if there are 4-8 ticks, and also that makes the plot easier to read. Here's an example:
```julia
plot([sin, cos], 0, 20, ribbon = 0.5) 
```
<img width="588" alt="skaermbillede 2017-10-03 kl 22 34 51" src="https://user-images.githubusercontent.com/8429802/31147846-59b67666-a88b-11e7-8e4e-ae9a176529d8.png">
I'd expect the ticks to be at 0, 5, 10, 15 and 20. Not sure about the y axis - but -2:2 would possibly be easier to read.

**Comment by mkborregaard** [comment]
As @piever points out,
```julia
plot([sin, cos], 0, 20, ribbon = 0.5, xlim = (0,20)) 
```
gives the right ticks on the x axis. The xlims and ylims appear to be just short of the sensible value:
```julia
xlims()
# (0.04882909509894066, 19.9364543200803)
ylims()
# (-1.4999971747424232, 1.4999963364314226)
```
Not sure what causes this. It is possible that `adapted_grid` could be responsible for the x axes being shifted slightly since I don't think Plots adds any x axis widening when `seriestype = :path`.

**Comment by mkborregaard** [comment]
Indeed when using
```
plot([sin, cos], 0, 20, ribbon = 0.5, markershape = :circle)
```
PlotUtils will widen the axes and you get
<img width="726" alt="skaermbillede 2017-10-04 kl 22 55 05" src="https://user-images.githubusercontent.com/8429802/31199290-34dedaaa-a957-11e7-93a1-d9eb412dd967.png">
(Note there's a bug that draws circles on the ribbon line too)

**Comment by mkborregaard** [comment]
It appears an easy fix would be to activate axis widening for seriestypes other than `:scatter`

**Comment by piever** [comment]
I'd be in favor of allowing axis widening, as it's very beneficial for ticks to have sensible lims. I guess in the plots without explicit x axis the problem will always arise because it's hard to tell which points the `adaptive_grid` algorithm will choose.

**Comment by daschw** [comment]
Another argument for allowing widening in general is that now thicker lines are cut, e.g. `plot(linspace(-π, π, 100), sin, lw = 10)`:
![allow_widen](https://user-images.githubusercontent.com/16589944/31316074-d5db9594-ac25-11e7-9db5-217f1744b537.png)
This would probably also be fixed in most cases by activating widen for other seriestypes.

**Comment by mkborregaard** [comment]
Also relevant: https://github.com/JuliaPlots/Plots.jl/pull/835

**Comment by mkborregaard** [comment]
Fixed
