### ISSUE TITLE
adapted_grid return both x and f(x) values

### ISSUE THREAD

**Issue by ivborissov** [JuliaPlots/PlotUtils.jl#48]
Hi, 
I belive it is useful to have `adapted_grid` returning both `x` values and `f(x)` vector.
like `return xs[2:end-1], fs[2:end-1]` 
Otherwise you have to calculate `f(x)` values twice to get a plot, which can be computationally expensive for complicated "black-box" functions.

**Comment by mkborregaard** [comment]
You're very welcome to submit a PR here and on Plots that implements this.

**Comment by BeastyBlacksmith** [comment]
Thats also fixed in https://github.com/JuliaPlots/PlotUtils.jl/pull/68.
