### ISSUE TITLE
White curve when palette=:grays

### ISSUE THREAD

**Issue by dpo** [JuliaPlots/PlotUtils.jl#55]
It seems important to support `palette=:grays` but I always get a white curve, which is then invisible:

```
plot([cumsum(randn(100)) cumsum(randn(100))], palette=:grays)
```
![grays](https://user-images.githubusercontent.com/38760/49823932-dbb2ba80-fd4e-11e8-82cd-f232f841b736.png)

Is there a way to select the grays so the lightest one is more visible?

Thanks!

**Comment by daschw** [comment]
You could manually set your own gradient with e.g.
```julia
plot([cumsum(randn(100)) cumsum(randn(100))], palette=cgrad([:grey, :black]))
```

**Comment by mkborregaard** [comment]
I'd suggest using `linestyle = :auto` for black-white plots instead.

**Comment by dpo** [comment]
Thank you, both suggestions help! For information, is there a "smart" way of excluding white from a color palette to avoid the mental effort of coming up with my own gradient?
