### ISSUE TITLE
optimized_ticks_typed produces persistent warnings

### ISSUE THREAD

**Issue by mkarikom** [JuliaPlots/PlotUtils.jl#58]
I tried this in Juno first:
Some plots trigger the warning "No strict ticks found", which appears over and over, and doesn't go away until the name is set to "nothing" or the session is restarted:
```julia
 julia> p = plot(my_fitted_parameters)
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
julia> a = 1
1
julia> ┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
julia> 
julia> p = nothing
julia> a = 1
1
```

Using REPL in the system terminal, this behavior dissapears.  
```julia
> julia> typeof(my_fitted_parameters)
Turing.Utilities.Chain{AbstractRange{Int64}}
julia> p = plot(my_fitted_params)
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
┌ Warning: No strict ticks found
└ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
GKS: Rectangle definition is invalid in routine SET_WINDOW
GKS: Rectangle definition is invalid in routine SET_WINDOW
julia> a = 1
1
julia> 
```
But I'm still not sure if this is a Juno issue or a PlotUtils issue.  I'm new to Julia but lot's of googling didn't turn up anything related to this behavior.

Here is the code to generate the plotted data:
```julia
using Turing
using StatsPlots
@model gdemo(x, y) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x ~ Normal(m, sqrt(s))
  y ~ Normal(m, sqrt(s))
end
my_fitted_parameters = sample(gdemo(1.5, 2), HMC(1000, 0.1, 5))
```

**Comment by mkarikom** [comment]
> I tried this in Juno first:
> Some plots trigger the warning "No strict ticks found", which appears over and over, and doesn't go away until the name is set to "nothing" or the session is restarted:
> 
> > julia> p = plot(my_fitted_parameters)
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > julia> a = 1
> > 1
> > julia> ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > julia>
> > julia> p = nothing
> > julia> a = 1
> > 1
> > julia>
> 
> Using REPL in the system terminal, this behavior dissapears.
> 
> > julia> typeof(my_fitted_params)
> > Turing.Utilities.Chain{AbstractRange{Int64}}
> > julia> p = plot(my_fitted_params)
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > ┌ Warning: No strict ticks found
> > └ @ PlotUtils ~/.julia/packages/PlotUtils/GxT73/src/ticks.jl:173
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > GKS: Rectangle definition is invalid in routine SET_WINDOW
> > julia> a = 1
> > 1
> > julia>
> 
> But I'm still not sure if this is a Juno issue or a PlotUtils issue. I'm new to Julia but lot's of googling didn't turn up anything related to this behavior.

**Comment by mkborregaard** [comment]
This is mostly a MCMCChains issue, not a Plots issue, and the MCMCChains issue will be fixed in https://github.com/TuringLang/MCMCChain.jl/pull/33 . It's a bit strange that the error is persistent, but I can't replicate that in Juno.

**Comment by mkborregaard** [comment]
I'll close for now - feel free to reopen if it continues with other data or after MCMCChain has been updated.
