### ISSUE TITLE
Unnecessary warning for matplotlib.jl with :gray?

### ISSUE THREAD

**Issue by ajkeith** [JuliaPlots/PlotUtils.jl#59]
The basic problem is that I want to set a plot element to the color `:gray` but I get a library clash (cmocean and colorcet) even though I've already specified `:Plots` as my library with `clibrary(:Plots)`. Here's a MWE:

```julia
using Plots
gr()
clibrary(:Plots)
plot(rand(10), seriescolor = :blue)
plot(rand(10), seriescolor = :lightgray)
plot(rand(10), seriescolor = :gray)
```
Resulting in the following warning:
```julia
┌ Warning: gray is found in more than one library: cmocean, colorcet. Choosing cmocean
└ @ PlotUtils C:\Users\AKeith\.julia\packages\PlotUtils\GxT73\src\color_gradients.jl:40
```
I took a look at the gradients folder, but I don't really understand how the gradients defined in matplotlib.jl (which I think corresponds to :Plots) translates to the color names used in symbols. I'm not sure why `:blue` and `:lightgray` don't cause name conflicts but `:gray` does. It's just a warning, so it's not affecting my code negatively but it seemed like it might be some kind of bug.

**Comment by mexsser** [comment]
Found this problem, too.

**Comment by ajkeith** [comment]
Great, thanks for the fix!
