### ISSUE TITLE
Floating point error in optimize_ticks

### ISSUE THREAD

**Issue by aahaselgrove** [JuliaPlots/PlotUtils.jl#66]
optimize_ticks uses `10.0^z` as part of the calculation for tickspan [code](https://github.com/JuliaPlots/PlotUtils.jl/blob/master/src/ticks.jl#L94). This has the potential to produce floating point errors, eg. `3 * 10.0^-2`, `6 * 10.0^-2`, `3 * 10.0^-5`.

**Comment by asinghvi17** [comment]
The relevant code is:
https://github.com/JuliaPlots/PlotUtils.jl/blob/226d3366a4d67458f1ac9e8f2501aa4b5b0324a2/src/ticks.jl#L94
(this is just a permalink to the same line you highlighted).
Here, you could theoretically round; however, I'm not sure how that would affect the behaviour of the optimizer.  Best way is to try it out and see 😄.
