### ISSUE TITLE
Generalize color palettes

### ISSUE THREAD

**Issue by ohmsweetohm1** [JuliaPlots/PlotUtils.jl#72]
Categorical palettes like `colorbrewer:Dark2` can not be represented with the existing `ColorGradient` since it's spectrum of colors can not be interpolated like the normal color gradients.

A `ColorPalette` is really an instance that can be obtained from a `ColorGradient` or is directly specified in the case of a categorical palette.

**Comment by mkborregaard** [comment]
Yes. I think it could be solved by having `getindex` (which does the interpolation) dispatch on the type, so that the index is rounded to a certain value before accessing the gradient.
