### ISSUE TITLE
Regression in Plots reference images.

### ISSUE THREAD

**Issue by daschw** [JuliaPlots/PlotUtils.jl#86]
I'm afraid I see a regression with this in the Plots tests.
![ticks](https://user-images.githubusercontent.com/16589944/76689039-a9b79480-6632-11ea-8c15-e8f160065162.png)
Compare the yticks in the first and the third subplot of the second row.
@jkrumbiegel Might this be caused by #83?

**Comment by jkrumbiegel** [comment]
I guess so? I'm skipping some of the rounding because it's slow, but that didn't seem to trip up tests.
https://github.com/JuliaPlots/PlotUtils.jl/commit/89e7316bfbabada15eae93db262e2103a9de2b96

**Comment by daschw** [comment]
Also
```julia
plot([1], [1])
```
![ticks](https://user-images.githubusercontent.com/16589944/77339785-9ab89c80-6d2c-11ea-8d80-a24a3485868f.png)

looks weird. Should we revert the changes in #83?
cc: @mkborregaard @asinghvi17

**Comment by mkborregaard** [comment]
Depends on whether these kinks are fixable I guess :-)
